package complaintsystem;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        manageComplainButton = new javax.swing.JButton();
        manageComplainButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		DeleteComplaint manageComplain=new DeleteComplaint();
        		manageComplain.setVisible(true);
        		setVisible(false);
        	}
        });
        searchComplainButton = new javax.swing.JButton();
        searchComplainButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		SearchComplaint searchComplain=new SearchComplaint();
        		searchComplain.setVisible(true);
        		setVisible(false);
        	}
        });
        updateComplainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Admin Menu");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Only admin"));

        manageComplainButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageComplainButton.setText("Manage Complain");

        searchComplainButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchComplainButton.setText("Search Complain");

        updateComplainButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateComplainButton.setText("Update Complain");
        updateComplainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	UpdateComplaint updateComplain=new UpdateComplaint();
            	updateComplain.setVisible(true);
        		setVisible(false);
            }
        });
        
        addStaffButton = new JButton();
        addStaffButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		AddStaff addStaff=new AddStaff();
        		addStaff.setVisible(true);
        		setVisible(false);
        	}
        });
        addStaffButton.setText("Add Staff");
        addStaffButton.setFont(new Font("Tahoma", Font.BOLD, 18));
        
        addOfficeButton = new JButton();
        addOfficeButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		AddOffice addOffice=new AddOffice();
        		addOffice.setVisible(true);
        		setVisible(false);
        	}
        });
        addOfficeButton.setText("Add Office");
        addOfficeButton.setFont(new Font("Tahoma", Font.BOLD, 18));
        
        adddRoomButton = new JButton();
        adddRoomButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		AddRoom addRoom=new AddRoom();
        		addRoom.setVisible(true);
        		setVisible(false);
        	}
        });
        adddRoomButton.setText("Add Room");
        adddRoomButton.setFont(new Font("Tahoma", Font.BOLD, 18));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(130)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(adddRoomButton, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        				.addComponent(addOfficeButton, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        				.addComponent(addStaffButton, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        				.addComponent(updateComplainButton, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        				.addComponent(searchComplainButton, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        				.addComponent(manageComplainButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(36)
        			.addComponent(manageComplainButton, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(searchComplainButton, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(updateComplainButton, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(addStaffButton, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(addOfficeButton, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(adddRoomButton, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(172)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(26)
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(26, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 451, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageComplainButton;
    private javax.swing.JButton searchComplainButton;
    private javax.swing.JButton updateComplainButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private JButton addStaffButton;
    private JButton addOfficeButton;
    private JButton adddRoomButton;
    // End of variables declaration//GEN-END:variables
}
